force-app/main/default/objects/Venta_Mostrador_Detalle__c/Venta_Mostrador_Detalle__c.object-meta.xml
<CustomObject>
    <description>Detalle ventas mostrador</description>
    <label>Ventas Mostrador Detalle</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Venta Mostrador Detalle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ventas Mostrador Detalles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/Descto__c.field-meta.xml
<CustomField>
    <fullName>Descto__c</fullName>
    <description>Descuento por posición</description>
    <inlineHelpText>Porcentaje de descuento que se otorga a la posición</inlineHelpText>
    <label>% Descto</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/Descuento_Monto__c.field-meta.xml
<CustomField>
    <fullName>Descuento_Monto__c</fullName>
    <label>Descuento Monto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/IVA__c.field-meta.xml
<CustomField>
    <fullName>IVA__c</fullName>
    <description>Monto IVA</description>
    <label>IVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <description>Codigo del material a vender</description>
    <inlineHelpText>Codigo del material a vender</inlineHelpText>
    <label>Material</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/POCH_Cantidad__c.field-meta.xml
<CustomField>
    <fullName>POCH_Cantidad__c</fullName>
    <label>Cantidad en Ordenes</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sucursal</label>
    <referenceTo>POCH_Sucursal__c</referenceTo>
    <relationshipLabel>Ventas Mostrador Detalles</relationshipLabel>
    <relationshipName>Ventas_Mostrador_Detalles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/UnidadMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadMedida__c</fullName>
    <label>UM Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Poch_Unidadmedida</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/Valor_neto__c.field-meta.xml
<CustomField>
    <fullName>Valor_neto__c</fullName>
    <label>Valor neto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Venta_Mostrador_Detalle__c/fields/Ventas_Mostrador__c.field-meta.xml
<CustomField>
    <fullName>Ventas_Mostrador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ventas Mostrador</label>
    <referenceTo>Ventas_Mostrador__c</referenceTo>
    <relationshipName>Ventas_Mostrador_Detalles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/Ventas_Mostrador__c.object-meta.xml
<CustomObject>
    <label>Ventas Mostrador</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Venta Mostrador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ventas Mostradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ventas Mostradores</relationshipLabel>
    <relationshipName>Ventas_Mostradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Condicion_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>Condicion_de_Pago__c</fullName>
    <label>Condición de Pago</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Credito_disponible__c.field-meta.xml
<CustomField>
    <fullName>Credito_disponible__c</fullName>
    <label>Línea de crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <label>Descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Digitos_tarjeta__c.field-meta.xml
<CustomField>
    <fullName>Digitos_tarjeta__c</fullName>
    <label>Ult. 4 Dígitos</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Correo Electronico del cliente</description>
    <inlineHelpText>Correo Electronico del cliente</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Enviado_SAP__c.field-meta.xml
<CustomField>
    <fullName>Enviado_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Id_cliente_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_cliente_SAP__c</fullName>
    <formula>Cliente__r.POCH_IDClienteSAP__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id cliente SAP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Id_Registro_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_Registro_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Numero de pedido SAP</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Importe_2__c.field-meta.xml
<CustomField>
    <fullName>Importe_2__c</fullName>
    <description>Importe de la da forma de pago</description>
    <inlineHelpText>Importe de la 2da forma de pago</inlineHelpText>
    <label>Importe 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Importe_3__c.field-meta.xml
<CustomField>
    <fullName>Importe_3__c</fullName>
    <description>Importe de la 3era forma de pago</description>
    <inlineHelpText>Importe de la 3era forma de pago</inlineHelpText>
    <label>Importe 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <description>Importe de la 1er forma de pago</description>
    <inlineHelpText>Importe de la 1er forma de pago</inlineHelpText>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/IVA__c.field-meta.xml
<CustomField>
    <fullName>IVA__c</fullName>
    <label>IVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Metodo_de_Pago2__c.field-meta.xml
<CustomField>
    <fullName>Metodo_de_Pago2__c</fullName>
    <description>2da forma de pago</description>
    <inlineHelpText>2da forma de pago</inlineHelpText>
    <label>Método de Pago 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Metodo_de_Pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Metodo_de_Pago3__c.field-meta.xml
<CustomField>
    <fullName>Metodo_de_Pago3__c</fullName>
    <description>3era forma de pago</description>
    <inlineHelpText>3era forma de pago</inlineHelpText>
    <label>Método de Pago 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Metodo_de_Pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Metodo_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>Metodo_de_Pago__c</fullName>
    <description>1er forma de pago</description>
    <inlineHelpText>1er forma de pago</inlineHelpText>
    <label>Método de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Metodo_de_Pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Name_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Name_Cliente__c</fullName>
    <description>Nombre del cliente</description>
    <formula>Cliente__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Nombre del cliente</inlineHelpText>
    <label>Nombre del Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Obs_Pago_2__c.field-meta.xml
<CustomField>
    <fullName>Obs_Pago_2__c</fullName>
    <description>Observaciones de la 2da forma de pago</description>
    <inlineHelpText>Observaciones de la 2da forma de pago</inlineHelpText>
    <label>Obs. Pago 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Obs_Pago_3__c.field-meta.xml
<CustomField>
    <fullName>Obs_Pago_3__c</fullName>
    <description>Observaciones de la 3era forma de pago</description>
    <inlineHelpText>Observaciones de la 3era forma de pago</inlineHelpText>
    <label>Obs. Pago 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Obs_Pago__c.field-meta.xml
<CustomField>
    <fullName>Obs_Pago__c</fullName>
    <description>Observaciones de la 1er forma de pago</description>
    <inlineHelpText>Observaciones de la 1er forma de pago</inlineHelpText>
    <label>Obs. Pago</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/OrganizacionVentas__c.field-meta.xml
<CustomField>
    <fullName>OrganizacionVentas__c</fullName>
    <label>Organización de Ventas</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/POCH_Sucursal__c.field-meta.xml
<CustomField>
    <fullName>POCH_Sucursal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sucursal</label>
    <referenceTo>POCH_Sucursal__c</referenceTo>
    <relationshipLabel>Ventas Mostradores</relationshipLabel>
    <relationshipName>Ventas_Mostradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Precio_total__c.field-meta.xml
<CustomField>
    <fullName>Precio_total__c</fullName>
    <label>Precio total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alta</fullName>
                <label>En Proceso</label>
            </value>
            <value>
                <fullName>Liberado a SAP</fullName>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Validación Crédito</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Con remisión</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Facturado</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Anulado</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Embarcado</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Entregado</label>
            </value>
            <value>
                <fullName>NE</fullName>
                <label>No Entregado</label>
            </value>
            <value>
                <fullName>RC</fullName>
                <label>Rechazado por Cliente</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nota de Crédito</label>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Uso_de_CFDI__c.field-meta.xml
<CustomField>
    <fullName>Uso_de_CFDI__c</fullName>
    <label>Uso de CFDI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Uso_de_CFDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Valor_Neto__c.field-meta.xml
<CustomField>
    <fullName>Valor_Neto__c</fullName>
    <description>Importe de venta de la posición</description>
    <inlineHelpText>Valor de (Cantidad*UM venta ) - Descuento</inlineHelpText>
    <label>Valor Neto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ventas_Mostrador__c/fields/Via_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Via_de_pago__c</fullName>
    <description>Metodo de pago de Facturacion</description>
    <inlineHelpText>Metodo de pago de Facturacion</inlineHelpText>
    <label>Vía de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Via_de_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/POCH_VentaMostrador_cls.cls
public class POCH_VentaMostrador_cls {
    /**
    Metodo para Obtener los detalles de inventario y mostarlos en el componente
    */
    @AuraEnabled
    public static Ventas_Mostrador__c getCabeceraVentaMostrador(String idCabeceraVentaMostrador) {
        Ventas_Mostrador__c cabecera = new Ventas_Mostrador__c();    
        
        cabecera = [SELECT 
                        Id, 
                        Name,
                        Cliente__c,
                        Name_Cliente__c,
                        Id_cliente_SAP__c,
                        POCH_Sucursal__r.Name,
                        POCH_Sucursal__r.POCH_Sociedad__c, 
                        CurrencyIsoCode,
                        Email__c,
                        Credito_disponible__c,
                        Digitos_tarjeta__c,
                        Via_de_pago__c, 
                        Condicion_de_Pago__c,
                        Metodo_de_Pago__c,
                        Metodo_de_Pago2__c,
                        Metodo_de_Pago3__c,
                        Importe__c,
                        Importe_2__c,
                        Importe_3__c,
                        Obs_Pago__c,
                        Obs_Pago_2__c,
                        Obs_Pago_3__c,
                        Valor_Neto__c,
                        Descuento__c,
                        Subtotal__c,
                        IVA__c,
                        Precio_total__c,
                        Id_Registro_SAP__c,
                        Status__c,
                        POCH_Sucursal__c,
                        Uso_de_CFDI__c,
                        Enviado_SAP__c,
                        OrganizacionVentas__c
                    FROM Ventas_Mostrador__c 
                    WHERE id =: idCabeceraVentaMostrador];
        system.debug(cabecera); 
        return cabecera; 
    }
    
    /**
    Metodo para Obtener los detalles de inventario y mostarlos en el componente
    */
    @AuraEnabled
    public static List<Venta_Mostrador_Detalle__c> getDetailsVentaMostrador(String idVentaMostrador) {
        List<Venta_Mostrador_Detalle__c> lstDetail = new List<Venta_Mostrador_Detalle__c>();    
        
        lstDetail = [SELECT 
                        Id, 
                        Name, 
                        CurrencyIsoCode, 
                        Material__c, 
                        Descto__c, 
                        Precio__c, 
                        Descripcion__c, 
                        POCH_Cantidad__c, 
                        UnidadMedida__c, 
                        Sucursal__c, 
                        Status__c,
                        IVA__c,
                        Descuento_Monto__c  
                    FROM Venta_Mostrador_Detalle__c 
                    WHERE Ventas_Mostrador__c =: idVentaMostrador];
        return lstDetail;
    }
    
    /*
    @Description:Obtiene datos iniciales de Inventario
    */
    @AuraEnabled
    public static Ventas_Mostrador__c getDataInv(String idInv) {
        return [SELECT Cliente__c,POCH_Sucursal__c,POCH_Sucursal__r.Name FROM Ventas_Mostrador__c WHERE Id =: idInv];
    }   

    /*
    @Description:Obtiene permisos de usuario actual
    */
    @AuraEnabled
    public static Boolean getAutorizacion(String idSuc) {
        if(String.isNotBlank(idSuc)) {
            String orgVts = [SELECT POCH_OrganizacionVentas__c FROM POCH_Sucursal__c WHERE Id =: idSuc OR Name =: idSuc LIMIT 1].POCH_OrganizacionVentas__c;            
            User usuario  = [SELECT Profile.Name,POCH_OrganizacionesVentas__c FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
            
            List<String> lSuc = usuario.POCH_OrganizacionesVentas__c.split(';');
            Set<String>  setSuc = new Set<String>();
            for(String suc : lSuc)
                setSuc.add(suc);
            
            
            if(!setSuc.contains(orgVts) && !usuario.Profile.Name.containsIgnoreCase('admin'))            
                return true;
        }        
        return false;
    } 
    
    // Metodo para Obtener los stocks y mostarlos en el componente
    @AuraEnabled
    public static List<POCH_DetalleInventario__c> getStocks(String idSheetDetail) {
        List<POCH_DetalleInventario__c> lstDetail = new List<POCH_DetalleInventario__c>();    
        
        lstDetail = [SELECT Id FROM POCH_DetalleInventario__c limit 10 ];
        return lstDetail;
    }
    
    /**
    Metodo para obtener los valores de picklist esto es dinamico por objeto , solo funciona para un nivel de picklist
    */
    @AuraEnabled        
    public static List<String> PickListValuesIntoList(String objectType, String selectedField) {
        List<String> pickListValuesList = new List<String>();
        Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get(objectType);
        Schema.DescribeSObjectResult res = convertToObj.getDescribe();
        Schema.DescribeFieldResult fieldResult = res.fields.getMap().get(selectedField).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry pickListVal : ple) {
            pickListValuesList.add(pickListVal.getLabel());
        }    
        return pickListValuesList;
    }
    
    /**
    Metodo para determinar el precio unitario
    */

     /**
    Metodo para obtener sucursal
    */
    @AuraEnabled
    public static Poch_Sucursal__c getSucursal(String idAccount) {
        User usuario  = [SELECT POCH_OrganizacionesVentas__c FROM User WHERE Id =: UserInfo.getUserId()];
        POCH_SucursalAmpliada__c sucursalAmp = [SELECT 
                                                    Id, 
                                                    Poch_Sucursal__c,
                                                    Poch_Sucursal__r.POCH_OrganizacionVentas__c
                                                FROM POCH_SucursalAmpliada__c 
                                                WHERE POCH_Cliente__c =: idAccount
                                                AND POCH_IdOrgVenta__c = '0029'];
                                                // AND POCH_IdOrgVenta__c =: usuario.POCH_OrganizacionesVentas__c];
        Poch_Sucursal__c organizacionVentas = [SELECT id, POCH_OrganizacionVentas__c FROM Poch_Sucursal__c WHERE id =: sucursalAmp.Poch_Sucursal__c];
        return organizacionVentas;
    }

    /**
    Metodo para obtener datos Account
    */
    @AuraEnabled
    public static Account getAccount(String idAccount) {
        Account cliente = [SELECT 
                                Id,
                                Name, 
                                POCH_IDClienteSAP__c,
                                CurrencyIsoCode,
                                POCH_CorreoElectronico__c,
                                POCH_ClasificacionFiscal__c
                            FROM Account 
                            WHERE Id =: idAccount];
        return cliente;
    }

    /**
    Metodo para obtener linea de credito
    */
    @AuraEnabled
    public static POCH_InformacionCredito__c getCreditLine(String idAccount) {
        User usuario  = [SELECT POCH_OrganizacionesVentas__c FROM User WHERE Id =: UserInfo.getUserId()];
        POCH_SucursalAmpliada__c sucursalAmp = [SELECT 
                                                    Id, 
                                                    Poch_Sucursal__c,
                                                    POCH_AreaControlCreditos__c 
                                                FROM POCH_SucursalAmpliada__c 
                                                WHERE POCH_Cliente__c =: idAccount
                                                //AND POCH_IdOrgVenta__c = '0029'];
                                                AND POCH_IdOrgVenta__c =: usuario.POCH_OrganizacionesVentas__c];

        POCH_InformacionCredito__c creditLine = [SELECT 
                                                    Id,
                                                    POCH_SaldoDisponible__c
                                                FROM POCH_InformacionCredito__c 
                                                WHERE POCH_Cliente__c =: idAccount
                                                AND POCH_AreaControlCredito__c =: sucursalAmp.POCH_AreaControlCreditos__c];
        return creditLine;
    }

    /**
    Metodo para obtener condition of pago
    */
    @AuraEnabled
    public static String getConditionPago(String idAccount) {
        String conditionPago = '';
        User usuario  = [SELECT POCH_OrganizacionesVentas__c FROM User WHERE Id =: UserInfo.getUserId()];
        POCH_SucursalAmpliada__c sucursalAmp = [SELECT 
                                                    Id, 
                                                    Condici_n_de_Pago__c
                                                FROM POCH_SucursalAmpliada__c 
                                                WHERE POCH_Cliente__c =: idAccount
                                                //AND POCH_IdOrgVenta__c = '0029'];
                                                AND POCH_IdOrgVenta__c =: usuario.POCH_OrganizacionesVentas__c];

        List<String> listDescription = new List<String>();
        Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get('POCH_SucursalAmpliada__c');
        Schema.DescribeSObjectResult res = convertToObj.getDescribe();
        Schema.DescribeFieldResult fieldResult = res.fields.getMap().get('Condici_n_de_Pago__c').getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for(Schema.PicklistEntry pickListVal : ple) {
                if (sucursalAmp.Condici_n_de_Pago__c == pickListVal.getValue()){
                    conditionPago = pickListVal.getLabel();
                }
                //pickListValuesList.add(pickListVal.getLabel());
            }   
        return conditionPago;
    }
    
    /**
    Metodo para obtener el description de un picklist dado el api name 
    */
    @AuraEnabled        
    public static List<String> getDescription(String objectType, String selectedField, List<String> listApiField) {
        List<String> listDescription = new List<String>();
        Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get(objectType);
        Schema.DescribeSObjectResult res = convertToObj.getDescribe();
        Schema.DescribeFieldResult fieldResult = res.fields.getMap().get(selectedField).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (String apiField : listApiField) {
            for(Schema.PicklistEntry pickListVal : ple) {
                if (apiField == pickListVal.getValue()){
                    listDescription.add(pickListVal.getLabel());
                }
                //pickListValuesList.add(pickListVal.getLabel());
            }   
        }
            
        return listDescription;
    }

    /**
    Metodo para validar la moneda vs la moneda de la sucursal 
    */
    @AuraEnabled        
    public static Boolean validarCurrency(String idAccount, String moneda) {
        Boolean currencyCorrect = false;
        User usuario  = [SELECT POCH_OrganizacionesVentas__c FROM User WHERE Id =: UserInfo.getUserId()];
        POCH_SucursalAmpliada__c sucursalAmp = [SELECT 
                                                    Id, 
                                                    Poch_Sucursal__c 
                                                FROM POCH_SucursalAmpliada__c 
                                                WHERE POCH_Cliente__c =: idAccount
                                                AND POCH_IdOrgVenta__c =: usuario.POCH_OrganizacionesVentas__c];
                                                //AND POCH_IdOrgVenta__c = '0029'];
        POCH_Sucursal__c sucursal = [SELECT Id, CurrencyIsoCode FROM POCH_Sucursal__c WHERE Id =: sucursalAmp.Poch_Sucursal__c];
        if (moneda == sucursal.CurrencyIsoCode){
            currencyCorrect = true;
        }
        return currencyCorrect;
    }

    /**
    Metodo para obtener listado de rate of currency 
    */
    @AuraEnabled        
    public static List<String> getRates() {
        List<String> listDescriptions = new List<String>();
        for(CurrencyType listRates :[SELECT Id, ConversionRate, IsCorporate, IsActive, IsoCode FROM CurrencyType WHERE IsActive = true]){
            listDescriptions.add(listRates.IsoCode + listRates.ConversionRate);
        }
        return listDescriptions;
    }

    /**
    Metodo para obtener el apiName de un picklist dado el label
    */
    @AuraEnabled        
    public static String getApiName(String objectType, String selectedField, String apiLabel) {
        String description = '';
        Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get(objectType);
        Schema.DescribeSObjectResult res = convertToObj.getDescribe();
        Schema.DescribeFieldResult fieldResult = res.fields.getMap().get(selectedField).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry pickListVal : ple) {
            if (apiLabel == pickListVal.getLabel()){
                description = pickListVal.getValue();
            } 
        }
            
        return description;
    }
}